### PR TITLE
Create role

### PR DESCRIPTION
**Pull request by tjoelsson**
## Summary of changes

Create role that installs memcached and igbinary extensions. When using pecl to install both modules, the memcached extension does not get compiled with igbinary support.

## How to Test

```
$ cd tests/
$ vagrant up --provision
```

### CODE REVIEW

**Comment by mark-juwai** [comment]
```
ERROR! the role 'php-memcached' was not found in /Users/juwai/Projects/ansible-role-php-memcached/tests/roles:/etc/ansible/roles:/Users/juwai/Projects/ansible-role-php-memcached/tests
```

**Comment by tjoelsson** [comment]
Forgot to commit the symlink. Sorry about that. Please try again.

**Comment by mark-juwai** [comment]
```
TASK [php-memcached : Configure memcached extension] ***************************
fatal: [default]: FAILED! => {"changed": true, "cmd": ["./configure", "--enable-memcached-igbinary"], "delta": "0:00:00.728145", "end": "2018-04-18 04:27:38.283424", "failed": true, "rc": 1, "start": "2018-04-18 04:27:37.555279", "stderr": "configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.\nconfigure: error: memcached support requires ZLIB. Use --with-zlib-dir=<DIR> to specify the prefix where ZLIB headers and library are located", "stderr_lines": ["configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers."
...
```

**Comment by tjoelsson** [comment]
Sorry about that. It should be working now. Please destroy box before running again.

**Review by mark-juwai — APPROVED** [review]

**Review by zhangjustin — APPROVED** [review]

**Pull request merged**
